const BLOGS = [
  {
    id: "llm-serving",
    tag: "LLM Infrastructure",
    title: "Serving LLMs In-House at Netflix: 46% Lower Cost at Scale",
    img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Sapphire-Radeon-HD-5570-Video-Card.jpg/1920px-Sapphire-Radeon-HD-5570-Video-Card.jpg",
    hook: "Announcement",
    body: [
      "<p>We are pleased to announce that Netflix now serves 78 percent of its LLM traffic on infrastructure we operate ourselves, up from zero a year ago. The move cuts cost per million tokens by 46 percent against our previous managed setup, with p99 latency flat and quality evals within noise. This post covers why we brought serving in-house, what the stack looks like across 64 GPUs, and the two-week measurement window that justified the investment.</p>",
      "<h3>The bill arrived first</h3>",
      "<p>Our LLM footprint grew from scattered experiments to production paths in under 12 months: summarization, support tooling, and three recommendation features now issue 380 million tokens per day, or 4.2 billion in a typical 11-day window. At that volume, managed inference pricing stopped being a convenience tax and became a line item, with a March 3 to March 16 measurement putting the annualized run rate at 3.1 million dollars. We sampled production traffic across all three use cases, replayed it against <a href='https://aws.amazon.com/bedrock/pricing/' class='text-verdict underline'>managed list pricing</a> and our own build cost, and found we could fund a dedicated serving team of 8 engineers several times over from the difference.</p>",
      "<img src='https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Printed_Circuit_Board_9990.jpg/1920px-Printed_Circuit_Board_9990.jpg' alt='Serving stack' class='rounded-2xl my-6 w-full object-cover'/>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 1: Requests flow through gateway, shape-aware scheduler, pooled GPUs, and prompt cache. One team owns the full path from prompt to token.</p>",
      "<h3>The stack in one paragraph, then the numbers</h3>",
      "<p>Requests land on a gateway that handles auth, rate limits, and routing across 3 production use cases in 4 regions. A shape-aware scheduler packs prompts onto pools of 64 H100 GPUs by sequence length, holding average utilization at 73 percent against 41 percent on our first naive placement. Models run on open runtimes with <a href='https://github.com/vllm-project/vllm' class='text-verdict underline'>vLLM</a> continuous batching and <a href='https://developer.nvidia.com/tensorrt-llm' class='text-verdict underline'>TensorRT-LLM</a> kernels, following the batching analysis in <a href='https://arxiv.org/abs/2305.06800' class='text-verdict underline'>Pope et al.</a>, with batch sizes up to 128 and a prefix cache absorbing 41 percent of repeated system prompts. Nothing here is exotic, and that is the point: the win is operational, because one team of 8 owns capacity, deploys, and on-call for the entire path.</p>",
      "<h3>Measured delta</h3>",
      "<p>Baseline: managed inference at March pricing over the March 3 to 16 window, 380 million tokens per day of production mix. Intervention: in-house rollout across all three use cases from April 7 to May 30. Result: cost fell from 1.82 dollars to 0.98 dollars per million tokens, a 46 percent reduction worth roughly 1.4 million dollars annualized. P99 latency moved from 1.12 seconds to 1.08 seconds across 12.6 million sampled requests. Human quality evals on 2,400 paired outputs landed within 0.4 points, inside annotator noise. The honest limit: bursty experimental workloads above 2.5x the daily peak still burst to managed capacity, where we pay the premium for 9 percent of tokens. Steady production traffic is where the math wins, and that is 91 percent of our volume.</p>",
      "<svg viewBox='0 0 640 300' class='my-6 w-full rounded-2xl border border-hairline' role='img' aria-label='Cost and latency before and after'><rect width='640' height='300' fill='#FFFFFF'/><text x='32' y='36' font-family='monospace' font-size='15' font-weight='bold' fill='#141412'>COST PER 1M TOKENS</text><rect x='32' y='52' width='380' height='34' fill='#141412'/><text x='420' y='77' font-family='monospace' font-size='15' fill='#141412'>$1.82 before</text><rect x='32' y='94' width='205' height='34' fill='#E50914'/><text x='245' y='119' font-family='monospace' font-size='15' fill='#141412'>$0.98 after</text><text x='32' y='168' font-family='monospace' font-size='15' font-weight='bold' fill='#141412'>P99 LATENCY</text><rect x='32' y='184' width='380' height='34' fill='#141412'/><text x='420' y='209' font-family='monospace' font-size='15' fill='#141412'>1.12s before</text><rect x='32' y='226' width='366' height='34' fill='#E50914'/><text x='406' y='251' font-family='monospace' font-size='15' fill='#141412'>1.08s after</text><text x='32' y='284' font-family='monospace' font-size='13' fill='#6B6B66'>MARCH 3 TO MAY 30 WINDOW</text></svg>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 2: Cost per million tokens down 46 percent from March baseline to May, with p99 latency flat at 1.1 seconds across 12.6M requests.</p>",
      "<h3>What is next?</h3>",
      "<p>Speculative decoding at a 1.8x acceptance rate and 32k-context batching are next, which our prototypes show cutting another 18 to 22 percent of GPU-hours on summarization. Thanks to the serving, capacity, and eval teams who carried the migration without a single customer-visible incident across 54 days. If serving infrastructure at 380 million tokens per day sounds fun, our team is hiring.</p>"
    ]
  },
  {
    id: "attestation",
    tag: "Security",
    title: "How Netflix Turns Cloud Roles into Internal Identity at Scale",
    img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Combination-lock-254923_1920.jpg/1920px-Combination-lock-254923_1920.jpg",
    hook: "Problem",
    body: [
      "<p>A Spark job on managed compute starts life with an AWS execution role and no internal identity, yet everything it touches inside Netflix needs the internal one: reading 1 of 840 encrypted columns, evaluating table ACLs across 34,000 Data Projects, or holding a session open for a 6-hour shuffle. Bridging that gap for 2.1 million daily job launches without weakening either side took real design work across 5 services. This is how we built the bridge we now trust with every byte.</p>",
      "<h3>Two identity systems, one trust decision</h3>",
      "<p>Internal service calls at Netflix authenticate on a private PKI with 15-minute certificates, mutual TLS, and issuance only after attestation, handling 9.4 billion authentications per day at a 22 millisecond median. Managed compute hands you a cloud identity from <a href='https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html' class='text-verdict underline'>AWS STS</a> and nothing else, valid for up to 6 hours with no knowledge of our projects. The translation between the two is where trust lives or dies, so we modeled it on <a href='https://spiffe.io/docs/latest/spiffe-about/overview/' class='text-verdict underline'>SPIFFE attestation</a> semantics: verify the platform, check the mapping, then mint the short-lived credential.</p>",
      "<img src='https://upload.wikimedia.org/wikipedia/commons/6/6f/Fingerprint_-_Plain_Whorl.jpg' alt='Identity exchange' class='rounded-2xl my-6 w-full object-cover'/>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 1: The control plane signs a workload payload at submit time. The identity service verifies the cloud role and issues a 15-minute certificate.</p>",
      "<h3>The mapping that makes it possible</h3>",
      "<p>Each Data Project maps one to one to a dedicated IAM role, recorded by the service that owns project metadata and audited every 24 hours. That mapping turns a provider statement (this process runs as role R) into an internal statement (this process is workload W) that our ACLs already understand. Our 34,000 projects shard deterministically across 12 accounts with at most 4,800 roles each, staying under the 5,000-role <a href='https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html' class='text-verdict underline'>IAM quota</a> while surviving 3x growth without re-sharding, and lookups complete in 4 milliseconds at p99 from a cache with a 98.7 percent hit rate.</p>",
      "<h3>How the exchange runs in 61 milliseconds</h3>",
      "<p>The control plane signs a workload payload at submit time in 8 milliseconds. A Spark plugin carries it to the identity service, which verifies the cloud role against STS in 22 milliseconds median and 61 milliseconds at p99, checks the project mapping, and issues a 15-minute certificate bound to the job attempt. <a href='https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html' class='text-verdict underline'>AWS STS acts as notary</a> throughout the 5-step exchange. Five components, one trust decision, 2.1 million issuances per day, and zero long-lived secrets on any of the 41,000 executors we measured in the May 12 to 26 window. When verification fails, which happens 0.03 percent of the time, the job fails closed with a structured error instead of a mysterious ACL denial 40 minutes later.</p>",
      "<svg viewBox='0 0 640 220' class='my-6 w-full rounded-2xl border border-hairline' role='img' aria-label='Exchange latency breakdown'><rect width='640' height='220' fill='#FFFFFF'/><text x='32' y='36' font-family='monospace' font-size='15' font-weight='bold' fill='#141412'>ONE EXCHANGE, FIVE STEPS</text><g font-family='monospace' font-size='14' font-weight='bold' text-anchor='middle'><rect x='16' y='70' width='100' height='64' rx='8' fill='#F4F3EF' stroke='#141412' stroke-width='2'/><text x='66' y='97' fill='#141412'>SUBMIT</text><text x='66' y='117' fill='#6B6B66' font-size='12'>4ms</text><rect x='140' y='70' width='100' height='64' rx='8' fill='#F4F3EF' stroke='#141412' stroke-width='2'/><text x='190' y='97' fill='#141412'>SIGN</text><text x='190' y='117' fill='#6B6B66' font-size='12'>2ms</text><rect x='264' y='70' width='100' height='64' rx='8' fill='#F4F3EF' stroke='#141412' stroke-width='2'/><text x='314' y='97' fill='#141412'>CARRY</text><text x='314' y='117' fill='#6B6B66' font-size='12'>0ms</text><rect x='388' y='70' width='100' height='64' rx='8' fill='#F4F3EF' stroke='#141412' stroke-width='2'/><text x='438' y='97' fill='#141412'>VERIFY</text><text x='438' y='117' fill='#6B6B66' font-size='12'>31ms</text><rect x='512' y='70' width='100' height='64' rx='8' fill='#E50914' stroke='#E50914' stroke-width='2'/><text x='562' y='97' fill='#FFFFFF'>ISSUE</text><text x='562' y='117' fill='#FFFFFF' font-size='12'>18ms</text></g><g stroke='#E50914' stroke-width='3'><line x1='116' y1='102' x2='140' y2='102'/><line x1='240' y1='102' x2='264' y2='102'/><line x1='364' y1='102' x2='388' y2='102'/><line x1='488' y1='102' x2='512' y2='102'/></g><text x='32' y='180' font-family='monospace' font-size='13' fill='#6B6B66'>MEDIAN 55MS END TO END, P99 210MS</text></svg>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 2: Median 22ms, p99 61ms end-to-end issuance across 2.1M daily launches. Failures fail closed at 0.03 percent.</p>",
      "<h3>What is next?</h3>",
      "<p>We are extending attestation to 2 more managed runtimes this half, covering 87 percent of remaining batch compute, and cutting p99 issuance below 40 milliseconds with regional caches. Thanks to the identity, data platform, and Spark teams who reviewed 14 threat-model revisions with us. If identity systems with 9.4 billion daily decisions are your thing, come build them with us.</p>"
    ]
  },
  {
    id: "genrec",
    tag: "Recommendations",
    title: "GenRec at Netflix: Recommendations as Language, 12% More Watching",
    img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Living_room_%28Unsplash%29.jpg/1920px-Living_room_%28Unsplash%29.jpg",
    hook: "Definition",
    body: [
      "<p>GenRec is a recommendation model that speaks fluent member: instead of 2,800 hand-crafted features over users, items, and interactions, it verbalizes 90 days of viewing history into 2,048 tokens and lets a large language model rank the catalog the way it completes text. Same task, new substrate, and in our January to March replay it earned 12.4 percent more sustained watching per visit. This post explains why tokens beat features, how we serve them inside the existing GPU budget, and where language still needs the old signals.</p>",
      "<h3>Why tokens beat 2,800 frozen features</h3>",
      "<p>Feature pipelines freeze yesterday's understanding of taste into columns that refresh every 24 hours and miss the order of the evening. A token stream stays raw across 14.2 million replayed sessions: what was watched, on what device, for how long, in what order, across 18,400 titles. The model sees the evening, not the aggregates, following the sequence-modeling line from <a href='https://arxiv.org/abs/1905.06874' class='text-verdict underline'>BERT4Rec</a> to <a href='https://arxiv.org/abs/2304.10149' class='text-verdict underline'>LLM ranking work</a>. In offline replay against the production ranker, GenRec variants won by 12.4 percent on sustained watching per visit, with the largest gains of 21.3 percent on unfamiliar titles where features are thinnest and only 3.1 percent on heavily watched hits where features already saturate.</p>",
      "<img src='https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Television_remote_control_-_unbranded-4028.jpg/1920px-Television_remote_control_-_unbranded-4028.jpg' alt='Token ranking' class='rounded-2xl my-6 w-full object-cover'/>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 1: Viewing history becomes a 2,048-token context paragraph. The model scores candidates as completions and the top completions become the row.</p>",
      "<h3>From events to rankings inside the GPU budget</h3>",
      "<p>History becomes a context paragraph of titles, interactions, and durations truncated at 2,048 tokens, covering 97 percent of 90-day histories in full. The model scores 480 candidates per row with prefill-only inference at 38 milliseconds median and 94 milliseconds at p99 on A10 GPUs, keeping serving cost inside the existing nightly GPU budget of 1,900 GPU-hours. Catalog scores refresh every 6 hours on the same cadence members browse, across <a href='https://netflixtechblog.com/system-architectures-for-personalization-and-recommendation-e081aa94b5d8' class='text-verdict underline'>our personalization stack</a>, and we rollback in 11 minutes when offline-online agreement drops below 0.92.</p>",
      "<h3>Measured delta over 90 days</h3>",
      "<p>Replay evaluation over 14.2 million sessions from January 6 to March 31 shows 12.4 percent lift in sustained watching per visit against the incumbent, significant at p less than 0.001 over 6 independent weekly slices. Gains concentrate where we hoped: 21.3 percent on titles with fewer than 50,000 lifetime plays and 4.2 percent on new members with 3 to 10 plays. The honest limit: cold-start members with zero history still need the old signals, trailing by 6.8 percent, so we route them to the feature ranker. Language needs something to read, and 11 percent of visits arrive with nothing to read yet.</p>",
      "<svg viewBox='0 0 640 260' class='my-6 w-full rounded-2xl border border-hairline' role='img' aria-label='Lift by title familiarity'><rect width='640' height='260' fill='#FFFFFF'/><text x='32' y='36' font-family='monospace' font-size='15' font-weight='bold' fill='#141412'>LIFT OVER INCUMBENT, 90-DAY REPLAY</text><rect x='32' y='60' width='440' height='44' fill='#E50914'/><text x='480' y='90' font-family='monospace' font-size='16' font-weight='bold' fill='#141412'>+21.3% unfamiliar</text><rect x='32' y='120' width='64' height='44' fill='#141412'/><text x='104' y='150' font-family='monospace' font-size='16' font-weight='bold' fill='#141412'>+3.1% hits</text><text x='32' y='200' font-family='monospace' font-size='13' fill='#6B6B66'>14.2M SESSIONS. COLD START STAYS ON INCUMBENT.</text></svg>",
      "<p class='text-xs text-folio font-medium -mt-3 mb-6'>Figure 2: Lift of 21.3 percent on unfamiliar titles versus 3.1 percent on hits across 14.2M replayed sessions. Cold-start routed to the incumbent.</p>",
      "<h3>What is next?</h3>",
      "<p>Multimodal context is next: artwork plus synopsis plus viewing in a single 4,096-token window, which early probes show adding another 5 to 7 percent on artwork-driven browsing. Thanks to the recommendations, ranking, and eval teams who labeled 2,400 pairs and ran 6 replay slices with us. The row is becoming a conversation, and our recommendations team is hiring.</p>"
    ]
  }
];
